apiVersion: apps/v1
kind: Deployment
metadata:
  name: actual
  labels:
    app: actual
spec:
  strategy:
    type: Recreate
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: actual
  template:
    metadata:
      labels:
        app: actual
    spec:
      containers:
        - name: actual
          image: actualbudget/actual-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5006
          volumeMounts:
            - mountPath: /app/user-files
              name: actual-data
          env:
            - name: ACTUAL_HOSTNAME
              value: {{ .Values.hostname }}
      volumes:
        - name: actual-data
          persistentVolumeClaim:
            claimName: actual-data