apiVersion: apps/v1
kind: Ingress
metadata:
  name: actual
  labels:
    app: actual
apiVersion: networking.k8s.io/v1
spec:
  tls:
    - hosts:
        - actual.{{ HOSTNAME }}
  rules:
    - host: actual.{{ HOSTNAME }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: actual
                port:
                  name: http
    - host: actual.{{ HOSTNAME }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: actual
                port:
                  name: http