apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: actual-ingress
  namespace: actual-server
  labels:
    app: actual
spec:
  tls:
  - hosts:
    - actual.310networks.com
  rules:
    - host: actual.310networks.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: actual
                port:
                  name: http