apiVersion: apps/v1
kind: Service
metadata:
  name: actual
  namespace: actual-server
  labels:
    app: actual
apiVersion: v1
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5006
      targetPort: http
  selector:
    app: actual