apiVersion: apps/v1
kind: Service
metadata:
  name: actual
  labels:
    app: actual
apiVersion: v1
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ PORT }}
      targetPort: http
  selector:
    app: actual